### ISSUE TITLE
possible outside matlab?

### ISSUE THREAD

**Issue by SB2020-eye** [AlejandroCallara/SmRG#2]
Hi. I was hoping to try out SmRG for a personal hobby project I'm working on. But I do not have matlab. Is there any possibility you know of to utilize SmRG outside of matlab? (In Python, for example?)

Just wondering. Thanks.

**Comment by AlejandroCallara** [comment]
Hi!

For the moment SmRG works only under MATLAB. 
I've considered to migrate to python more than one time, but I've still got to find the time to do it. 

I'm sorry I can't be helpful.
Alejandro

**Comment by SB2020-eye** [comment]
I understand. Thank you for letting me know. (If anything changes, and if you think of it, perhaps you can reply to this same thread again -- then I will get an email notification.)

All the best.
